### ISSUE TITLE
Any chance of a build supporting netstandard2.0?

### ISSUE THREAD

**Issue by jskeet** [emmettnicholas/StacMan#11]
I suspect the current code will *work* with .NET Core apps, but it would be nice to be more specific about it by explicitly targeting netstandard2.0.

I realize this project may be seen as "mostly legacy" now, so completely understand if the request is rejected :)

**Comment by emmettnicholas** [comment]
Thanks-- I'm a bit removed from the .NET game at the moment, so would have trouble easily verifying whether it works with .NET Core. You're right that this "mostly legacy" at this point, but is the suggestion to just update the README, or is there something else I'd need to do as well?

**Comment by jskeet** [comment]
It would involve updating the build process and creating a new release. If you're not doing much .NET work at the moment, it's probably not worth it :)

I'm just updating my web sites to use ASP.NET Core at the moment - if I can't get StacMan to work, I'll just look at alternatives... thanks!

**Comment by petrsvihlik** [comment]
@emmettnicholas Have you considered involving more people in this project? I personally would be interested in reviving and maintaining this project. With just a little care it could be up to the current .NET standards again.

@jskeet We use StacMan internally in our company and I too would appreciate if it targeted netstandard2.0. (Btw - did you go with an alternative solution in the end?)
